version: 0.2

env:
  variables: #Parameters related to the Test Runner and for the Project to parse jSON report to qTest
    REGION: "us-west-2"
    environment: "DEV"
    contactInitials: "JGS"
    requestedParser: "Cucumber_V2"
    cycleId: "182230"
    BuildNum: $CODEBUILD_BUILD_NUMBER
    atmId: "AA00001364"
    aut: "TESS"
    projectId: "54"
    reportFilePath: "target/cucumber-reports/adv"
    reportFileName: "cucumber-json-testng-report.json"
    testName: "TessWebsite-smoke-test"
    TERRAFORM_VER: 1.0.5

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto8
      python: 3.9
  pre_build:
    commands:
      - aws --version
      - npm install -g aws-cdk
      - cdk --version
      - pip install --upgrade pip
      - pip install requests
      - wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform_1.0.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      
  build:
    commands:
      #commands compile source code
      - echo Running maven commaned to execute tests
      - echo build number $CODEBUILD_BUILD_NUMBER
      - cd drivers
      - chmod 777 chromedriver
      - chmod +x chromedriver
      - cd ..
      - echo Build started on `date` 
      - aws s3 cp  s3://tess-web-artifacts/terraform/terraform.tfstate .
      - terraform init
      - terraform plan
     # - terraform apply -auto-approve
     # - docker-compose -f  docker-compose.yml up -d
      - mvn clean test -Dspring.profiles.active=DEV
      #- docker-compose -f  docker-compose.yml down -d
      - terraform destroy -auto-approve
      - aws s3 cp terraform.tfstate s3://tess-web-artifacts/terraform/terraform.tfstate.afterdestroy
           
  post_build:
    on-failure: CONTINUE
    commands:
      - echo Run Python script to upload report to qTest
      - python uploadResultsQtest.py         
      
reports:   
  tessweb-ReportGroup: #Cucumber reports from json plugin
    files:
      - 'target/cucumber-reports/adv/cucumber-json-testng-report.json'
    file-format: CUCUMBERJSON #Type of the report, defaults to JUNITXML

artifacts:
    files:
      - target/cucumber-reports/adv/cucumber-json-testng-report.json
  #files: imagedefinitions.json
   # - '**/*'
 # base-directory: 'dist'
