version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto8
  pre_build:
    commands:
      - aws --version
      - npm install -g aws-cdk
      - cdk --version
      #- npm install -g yarn
     # - yarn --version
      #- pip install --upgrade pip
      
  build:
    commands:
      #commands compile source code
      - echo Running maven commaned to execute tests
      - cd drivers
      - chmod 777 chromedriver
      - chmod +x chromedriver
      - cd ..
      - echo Build started on `date` 
      - docker-compose -f  docker-compose.yml up -d
      - mvn clean test -Dspring.profiles.active=DEV


      
  post_build:
    commands:
      - echo Build completed on `date`
      
reports:   
  tessweb-ReportGroup: #Cucumber reports from json plugin
    files:
      - 'target/cucumber-reports/adv/cucumber-json-testng-report.json'
    file-format: CUCUMBERJSON #Type of the report, defaults to JUNITXML

artifacts:
    files:
      - target/cucumber-reports/adv/cucumber-json-testng-report.json
  #files: imagedefinitions.json
   # - '**/*'
 # base-directory: 'dist'
